"""
ICSE Class V Social Studies - Complete Chapter Data
Each chapter has search keywords mapped to Wikipedia topics and trivia categories.
"""

CHAPTERS = {
    "Geography": [
        {
            "num": 1,
            "title": "Motions of the Earth",
            "emoji": "🌍",
            "wiki_queries": [
                "Earth's rotation and revolution",
                "rotation of Earth",
                "axial tilt of Earth",
                "seasons on Earth",
                "leap year",
                "equinox and solstice",
            ],
            "trivia_categories": [17],  # Science
            "key_concepts": [
                "Rotation — Earth spins on its axis (takes ~24 hours)",
                "Revolution — Earth orbits the Sun (takes ~365.25 days)",
                "Day and Night are caused by Rotation",
                "Seasons are caused by Revolution + Axial Tilt (23.5°)",
                "Equinox — equal day and night (March 21 & Sept 23)",
                "Solstice — longest/shortest day (June 21 & Dec 22)",
                "Leap Year — extra day every 4 years to correct calendar",
            ],
            "fun_fact": "Venus rotates in the opposite direction to most planets, so the Sun rises in the west on Venus!",
            "discussion_questions": [
                "What would happen if the Earth stopped rotating?",
                "Why do we have different seasons?",
                "Why is a leap year necessary?",
            ],
        },
        {
            "num": 2,
            "title": "Latitudes and Longitudes",
            "emoji": "📍",
            "wiki_queries": [
                "Latitude and longitude",
                "equator",
                "prime meridian",
                "tropic of cancer",
                "tropic of capricorn",
                "arctic circle",
                "antarctic circle",
                "coordinate system geography",
                "International Date Line",
            ],
            "trivia_categories": [22],  # Geography
            "key_concepts": [
                "Latitude — horizontal lines (parallels) measuring N-S from Equator (0°)",
                "Longitude — vertical lines (meridians) measuring E-W from Prime Meridian (0°)",
                "Equator — 0° latitude, divides Earth into Northern & Southern Hemispheres",
                "Prime Meridian — 0° longitude, passes through Greenwich, London",
                "Tropic of Cancer — 23.5°N",
                "Tropic of Capricorn — 23.5°S",
                "Arctic Circle — 66.5°N, Antarctic Circle — 66.5°S",
                "International Date Line — roughly 180° longitude",
                "India lies between 8°N–37°N latitude and 68°E–97°E longitude",
            ],
            "fun_fact": "The intersection of the Equator and Prime Meridian is in the Gulf of Guinea, in the Atlantic Ocean — there's no land there!",
            "discussion_questions": [
                "Why is the Prime Meridian important?",
                "How do latitudes and longitudes help in navigation?",
                "What is the significance of the Tropic of Cancer for India?",
            ],
        },
        {
            "num": 3,
            "title": "Weather and Climate",
            "emoji": "🌤️",
            "wiki_queries": [
                "weather and climate difference",
                "elements of weather",
                "temperature",
                "humidity",
                "atmospheric pressure",
                "wind",
                "precipitation",
                "weather forecasting",
            ],
            "trivia_categories": [17],
            "key_concepts": [
                "Weather — short-term condition of the atmosphere (changes daily)",
                "Climate — long-term average weather pattern of a place (over 30+ years)",
                "Elements of Weather: Temperature, Humidity, Rainfall, Wind, Pressure",
                "Temperature — how hot or cold the air is (measured by thermometer)",
                "Humidity — moisture in the air",
                "Rainfall — water falling from clouds",
                "Wind — moving air caused by differences in air pressure",
                "Weather instruments: Barometer, Thermometer, Wind Vane, Rain Gauge",
            ],
            "fun_fact": "The hottest temperature ever recorded on Earth was 56.7°C (134°F) in Death Valley, California in 1913!",
            "discussion_questions": [
                "How is weather different from climate?",
                "What instruments measure weather?",
                "Why does it rain more in some places than others?",
            ],
        },
        {
            "num": 4,
            "title": "Major Temperature Zones of the Earth",
            "emoji": "🌡️",
            "wiki_queries": [
                "climate zones of Earth",
                "torrid zone",
                "temperate zone",
                "frigid zone",
                "Koppen climate classification",
            ],
            "trivia_categories": [22],
            "key_concepts": [
                "Torrid Zone (Hot Zone) — between Tropic of Cancer & Tropic of Capricorn (0°–23.5° N/S)",
                "Temperate Zone — between Tropics and Arctic/Antarctic Circles",
                "Frigid Zone (Cold Zone) — near the poles, beyond Arctic/Antarctic Circles",
                "Torrid Zone: Direct sunlight, very hot, receives maximum heat",
                "Temperate Zone: Moderate temperature, four distinct seasons",
                "Frigid Zone: Extremely cold, ice-covered, receives slanting sunlight",
                "India lies mainly in the Torrid and Temperate zones",
            ],
            "fun_fact": "Antarctica, in the Frigid Zone, is the coldest, driest, and windiest continent on Earth!",
            "discussion_questions": [
                "Why is the Torrid Zone the hottest?",
                "In which zone does India fall?",
                "Why do the Frigid Zones receive very little sunlight?",
            ],
        },
        {
            "num": 5,
            "title": "Climate of India",
            "emoji": "🇮🇳",
            "wiki_queries": [
                "climate of India",
                "Indian monsoon",
                "seasons in India",
                "southwest monsoon India",
                "northeast monsoon India",
                "mango shower",
                "loo wind India",
            ],
            "trivia_categories": [22],
            "key_concepts": [
                "India has a tropical monsoon climate",
                "Four seasons: Winter (Dec–Feb), Summer (Mar–May), Monsoon (Jun–Sep), Post-Monsoon (Oct–Nov)",
                "Southwest Monsoon — brings heavy rainfall (Jun–Sep), crucial for agriculture",
                "Northeast Monsoon — brings rain to Tamil Nadu coast (Oct–Dec)",
                "Mango Showers — pre-monsoon rain in Kerala/Karnataka, helps mangoes ripen",
                "Loo — hot, dry wind in Northern India during summer",
                "India receives most of its rainfall from the monsoons",
                "Western coast & Northeast India receive heavy rainfall; Rajasthan is the driest",
            ],
            "fun_fact": "Mawsynram in Meghalaya receives the highest average rainfall in the world — over 11,000 mm per year!",
            "discussion_questions": [
                "Why is the monsoon so important for India?",
                "What are the four seasons of India?",
                "What is the Loo and where is it experienced?",
            ],
        },
        {
            "num": 6,
            "title": "Natural Vegetation of India",
            "emoji": "🌿",
            "wiki_queries": [
                "natural vegetation of India",
                "tropical rainforest India",
                "deciduous forest India",
                "thorn forest India",
                "mangrove forest India Sundarbans",
                "montane forest India",
                "grassland India",
            ],
            "trivia_categories": [22],
            "key_concepts": [
                "Natural vegetation — plants that grow naturally without human help",
                "Tropical Evergreen Forests — heavy rain, dense trees, found in Western Ghats, NE India",
                "Tropical Deciduous Forests — most widespread, trees shed leaves in dry season",
                "Thorn Forests & Scrubs — arid regions, Rajasthan, Gujarat",
                "Mangrove Forests — coastal areas, Sundarbans (home to Royal Bengal Tigers)",
                "Montane Forests — found in mountains, change with altitude",
                "Grasslands — found in parts of Deccan Plateau and Himalayan region",
            ],
            "fun_fact": "The Sundarbans is the largest mangrove forest in the world and is home to the endangered Royal Bengal Tiger!",
            "discussion_questions": [
                "What type of forest is most common in India?",
                "Why are mangrove forests important?",
                "How does altitude affect vegetation in mountains?",
            ],
        },
        {
            "num": 7,
            "title": "India's Natural Resources",
            "emoji": "⛏️",
            "wiki_queries": [
                "natural resources of India",
                "minerals in India",
                "water resources India",
                "soil types India",
                "forest resources India",
                "solar energy India",
                "coal reserves India",
                "iron ore India",
            ],
            "trivia_categories": [22],
            "key_concepts": [
                "Natural Resources — materials from nature that are useful to humans",
                "Types: Renewable (water, forest, solar) and Non-renewable (coal, minerals, petroleum)",
                "India is rich in iron ore, coal, manganese, bauxite, and mica",
                "Major coal regions: Jharkhand, Odisha, Chhattisgarh",
                "Major iron ore: Jharkhand, Odisha, Karnataka, Goa",
                "India has diverse soil types: Alluvial, Black, Red, Laterite",
                "Water resources: Rivers (Ganga, Brahmaputra, Godavari), lakes, groundwater",
                "Forest cover: About 24% of India's total area",
            ],
            "fun_fact": "India is the world's largest producer of mica, accounting for about 60% of global production!",
            "discussion_questions": [
                "What is the difference between renewable and non-renewable resources?",
                "Why should we conserve natural resources?",
                "Name some important minerals found in India.",
            ],
        },
        {
            "num": 8,
            "title": "Agriculture in India",
            "emoji": "🌾",
            "wiki_queries": [
                "agriculture in India",
                "types of farming in India",
                "Kharif crop",
                "Rabi crop",
                "Zaid crop",
                "Green Revolution India",
                "irrigation in India",
                "major crops of India",
            ],
            "trivia_categories": [22],
            "key_concepts": [
                "Agriculture — growing of crops and rearing of animals",
                "India is an agrarian country — about 50% population depends on agriculture",
                "Types of Farming: Subsistence, Commercial, Plantation, Intensive, Extensive",
                "Kharif Crops — sown in monsoon (June–July), harvested in autumn (e.g., Rice, Maize, Cotton)",
                "Rabi Crops — sown in winter (October–November), harvested in spring (e.g., Wheat, Gram, Mustard)",
                "Zaid Crops — grown between Rabi and Kharif (e.g., Cucumber, Watermelon)",
                "Green Revolution (1960s) — increased food grain production using HYV seeds",
                "Major rice-producing states: West Bengal, Punjab, Uttar Pradesh",
                "Major wheat-producing states: Uttar Pradesh, Punjab, Haryana",
            ],
            "fun_fact": "India is the second-largest producer of rice and wheat in the world, after China!",
            "discussion_questions": [
                "What is the difference between Kharif and Rabi crops?",
                "What was the Green Revolution?",
                "Why is agriculture called the backbone of India's economy?",
            ],
        },
        {
            "num": 9,
            "title": "Industry in India",
            "emoji": "🏭",
            "wiki_queries": [
                "industries in India",
                "textile industry India",
                "iron and steel industry India",
                "IT industry India Bangalore",
                "cotton textile industry India Mumbai",
                "jute industry India",
                "industrial regions of India",
            ],
            "trivia_categories": [22],
            "key_concepts": [
                "Industry — production of goods using machines and labour",
                "Types: Agro-based, Mineral-based, Forest-based, IT/Service-based",
                "Textile Industry — one of the oldest (cotton, silk, jute, wool)",
                "Major cotton textile centres: Mumbai, Ahmedabad, Coimbatore, Kolkata",
                "Iron & Steel — Jamshedpur (TISCO), Bhilai, Durgapur, Rourkela, Bokaro",
                "IT Industry — Bangalore (India's Silicon Valley), Hyderabad, Pune, Chennai",
                "Jute Industry — concentrated along the Hooghly River near Kolkata",
                "India has both large-scale and small-scale (cottage) industries",
            ],
            "fun_fact": "Jamshedpur is named after Jamsetji Tata, the founder of the Tata Iron and Steel Company (TISCO) in 1907!",
            "discussion_questions": [
                "What are the different types of industries?",
                "Why is Mumbai a major industrial centre?",
                "What is the importance of the IT industry in India?",
            ],
        },
        {
            "num": 10,
            "title": "Natural Disasters",
            "emoji": "🌪️",
            "wiki_queries": [
                "natural disaster",
                "earthquake",
                "flood",
                "cyclone",
                "tsunami",
                "drought",
                "landslide",
                "volcanic eruption",
                "disaster management India",
                "NDMA India",
            ],
            "trivia_categories": [17],
            "key_concepts": [
                "Natural Disaster — a sudden event caused by nature that causes great damage",
                "Earthquakes — caused by movement of tectonic plates under Earth's surface",
                "Floods — overflow of water, common during monsoons in India",
                "Cyclones — violent storms with strong winds, common in Bay of Bengal",
                "Tsunami — large ocean waves caused by underwater earthquakes",
                "Drought — long period without rain, affects agriculture",
                "Landslide — downward movement of soil/rocks on slopes",
                "Disaster Management — preparation, rescue, and recovery from disasters",
                "NDMA — National Disaster Management Authority of India",
            ],
            "fun_fact": "The 2004 Indian Ocean Tsunami was one of the deadliest natural disasters ever, affecting 14 countries!",
            "discussion_questions": [
                "What are the major natural disasters in India?",
                "What should we do during an earthquake?",
                "What is disaster management?",
            ],
        },
    ],
    "History": [
        {
            "num": 11,
            "title": "India's Material Heritage",
            "emoji": "🏛️",
            "wiki_queries": [
                "material heritage of India",
                "Indus Valley Civilization",
                "art and architecture of ancient India",
                "Ajanta Ellora caves",
                "Sanchi Stupa",
                "Indian pottery history",
                "ancient Indian coins",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Heritage — things passed down from the past (monuments, art, coins, etc.)",
                "Material Heritage — physical things we can see and touch",
                "Indus Valley Civilization (3300–1300 BCE) — well-planned cities with drainage systems",
                "Sanchi Stupa — Buddhist monument built by Emperor Ashoka",
                "Ajanta & Ellora Caves — rock-cut caves with beautiful paintings and sculptures",
                "Ancient Indian coins — tell us about trade, kings, and culture",
                "Pottery & Seals — Indus Valley seals show animals and script we can't fully read",
                "Temples — built in different styles (Nagara, Dravida, Vesara)",
            ],
            "fun_fact": "Indus Valley cities like Mohenjo-daro had indoor toilets and covered drainage systems over 4,500 years ago — before most of the ancient world!",
            "discussion_questions": [
                "What is the difference between material and non-material heritage?",
                "Why are the Ajanta Caves famous?",
                "What do ancient coins tell us about the past?",
            ],
        },
        {
            "num": 12,
            "title": "India's Non-material Heritage",
            "emoji": "🎭",
            "wiki_queries": [
                "intangible cultural heritage India",
                "Indian classical dance",
                "Indian classical music",
                "Indian festivals",
                "yoga UNESCO heritage",
                "Indian folklore",
                "traditional Indian art forms",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Non-material Heritage — things we cannot touch but are part of our culture",
                "Classical Dances: Bharatanatyam, Kathak, Odissi, Kuchipudi, Manipuri, Mohiniyattam, Kathakali, Sattriya",
                "Classical Music: Hindustani (North) & Carnatic (South)",
                "Yoga — recognized by UNESCO as Intangible Cultural Heritage",
                "Festivals: Diwali, Holi, Eid, Christmas, Pongal, Bihu, Onam, etc.",
                "Oral Traditions — folk tales, songs, proverbs passed through generations",
                "Traditional Art Forms: Madhubani, Warli, Pattachitra, Kalamkari",
                "Languages — India has 22 officially recognized languages",
            ],
            "fun_fact": "India has 8 classical dance forms and 2 classical music traditions, each with roots going back thousands of years!",
            "discussion_questions": [
                "Give examples of India's non-material heritage.",
                "Why is it important to preserve our heritage?",
                "Name some classical dance forms of India.",
            ],
        },
        {
            "num": 13,
            "title": "New Ideas in Europe",
            "emoji": "💡",
            "wiki_queries": [
                "Renaissance Europe",
                "Age of Exploration",
                "printing press Gutenberg",
                "Reformation Europe",
                "Scientific Revolution",
                "Industrial Revolution",
                "Age of Enlightenment",
                "French Revolution",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Renaissance (14th–17th century) — rebirth of art, science, and learning in Europe",
                "Gutenberg's Printing Press (1440) — made books cheaper, spread knowledge",
                "Age of Exploration — European sailors discovered new sea routes to India",
                "Reformation — movement to reform the Christian Church, led by Martin Luther",
                "Scientific Revolution — new discoveries in science (Copernicus, Galileo, Newton)",
                "Age of Enlightenment — ideas of liberty, equality, and reason",
                "French Revolution (1789) — people overthrew the monarchy, 'Liberty, Equality, Fraternity'",
                "Industrial Revolution — machines replaced hand labour, started in England",
            ],
            "fun_fact": "Before the printing press, a single book could take months to copy by hand! Gutenberg's invention changed the world forever.",
            "discussion_questions": [
                "What was the Renaissance and why was it important?",
                "How did the printing press change the world?",
                "What was the French Revolution about?",
            ],
        },
        {
            "num": 14,
            "title": "The English Come to India",
            "emoji": "🚢",
            "wiki_queries": [
                "British East India Company",
                "Battle of Plassey",
                "Battle of Buxar",
                "Doctrine of Lapse",
                "British Raj India",
                "Vasco da Gama India",
                "trade history British India",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Vasco da Gama (1498) — first European to reach India by sea route",
                "East India Company — British trading company that came to India in 1600s",
                "Started as traders, gradually became rulers",
                "Battle of Plassey (1757) — Robert Clive defeated Siraj-ud-Daulah",
                "Battle of Buxar (1764) — British gained control over Bengal, Bihar, Odisha",
                "Doctrine of Lapse — policy to annex Indian kingdoms with no male heir",
                "British introduced railways, postal system, English education, but also exploited India",
            ],
            "fun_fact": "The East India Company was originally just a group of merchants who wanted to trade spices! It eventually controlled most of India.",
            "discussion_questions": [
                "How did the British transform from traders to rulers?",
                "What was the significance of the Battle of Plassey?",
                "What were some positive and negative effects of British rule?",
            ],
        },
        {
            "num": 15,
            "title": "Freedom",
            "emoji": "🇮🇳",
            "wiki_queries": [
                "Indian independence movement",
                "Revolt of 1857",
                "Mahatma Gandhi",
                "non-cooperation movement",
                "civil disobedience movement",
                "Quit India Movement",
                "Indian National Congress",
                "Subhas Chandra Bose",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Revolt of 1857 — first major revolt against British rule (also called Sepoy Mutiny)",
                "Indian National Congress (1885) — founded to fight for Indian rights",
                "Mahatma Gandhi — Father of the Nation, leader of freedom struggle",
                "Non-Cooperation Movement (1920) — Indians refused to cooperate with British",
                "Civil Disobedience Movement (1930) — Salt March (Dandi March) led by Gandhi",
                "Quit India Movement (1942) — 'Do or Die' call by Gandhi",
                "Subhas Chandra Bose — formed the Indian National Army (INA)",
                "India gained independence on 15th August, 1947",
            ],
            "fun_fact": "The Dandi March covered 385 km! Gandhi and 78 followers walked from Sabarmati Ashram to Dandi to make salt, protesting the British salt tax.",
            "discussion_questions": [
                "Who was the first Indian to start the freedom struggle?",
                "What role did Mahatma Gandhi play in India's independence?",
                "What was the Quit India Movement?",
            ],
        },
        {
            "num": 16,
            "title": "They Fought against Inequality",
            "emoji": "✊",
            "wiki_queries": [
                "social reformers of India",
                "Raja Ram Mohan Roy",
                "Jyotirao Phule",
                "Savitribai Phule",
                "Dr. B.R. Ambedkar",
                "Ishwar Chandra Vidyasagar",
                "Mother Teresa",
                "women empowerment India history",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Social reformers worked to remove unfair practices from society",
                "Raja Ram Mohan Roy — abolished Sati, founded Brahmo Samaj",
                "Jyotirao Phule — fought for education of girls and lower castes",
                "Savitribai Phule — first female teacher of India",
                "Dr. B.R. Ambedkar — fought for rights of Dalits, drafted Indian Constitution",
                "Ishwar Chandra Vidyasagar — supported widow remarriage, girls' education",
                "Mother Teresa — served the poor and sick in Kolkata",
                "These reformers fought against caste discrimination, child marriage, Sati, and untouchability",
            ],
            "fun_fact": "Savitribai Phule started a school for girls in 1848 when it was considered unacceptable for girls to get an education!",
            "discussion_questions": [
                "Who was Raja Ram Mohan Roy and what did he do?",
                "What was the practice of Sati?",
                "Why is Dr. Ambedkar called the Father of the Indian Constitution?",
            ],
        },
        {
            "num": 17,
            "title": "What Influences History?",
            "emoji": "📜",
            "wiki_queries": [
                "sources of history",
                "archaeology",
                "inscriptions",
                "manuscripts",
                "coins in history",
                "monuments as historical evidence",
                "oral tradition history",
                "how historians study the past",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "History is the study of the past based on evidence",
                "Archaeological Sources: monuments, coins, pottery, tools, inscriptions",
                "Literary Sources: manuscripts, books, chronicles, religious texts",
                "Inscriptions — writings on stone or metal pillars (like Ashoka's edicts)",
                "Manuscripts — handwritten documents on palm leaves, bark, or paper",
                "Coins — tell us about rulers, dates, trade, and economy",
                "Oral Traditions — folk songs, stories passed down through generations",
                "Monuments — buildings and structures that tell us about architecture and culture",
                "Historians use all these sources to piece together the past",
            ],
            "fun_fact": "The Rosetta Stone helped historians decode Egyptian hieroglyphics because it had the same text in three different scripts!",
            "discussion_questions": [
                "What are the different sources of history?",
                "Why are coins important for historians?",
                "How do archaeologists help us understand the past?",
            ],
        },
    ],
    "Civics": [
        {
            "num": 18,
            "title": "The Constitution of India",
            "emoji": "📖",
            "wiki_queries": [
                "Constitution of India",
                "preamble of India",
                "fundamental rights India",
                "fundamental duties India",
                "directive principles of state policy India",
                "Dr. B.R. Ambedkar constitution",
                "Indian Constitution features",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Constitution — the supreme law of a country that defines how it is governed",
                "Indian Constitution came into force on 26th January, 1950 (Republic Day)",
                "Drafting Committee Chairman: Dr. B.R. Ambedkar",
                "Preamble — 'We the People of India' — declares India as Sovereign, Socialist, Secular, Democratic Republic",
                "Fundamental Rights — 6 basic rights guaranteed to every citizen (Right to Equality, Freedom, etc.)",
                "Fundamental Duties — 11 duties every citizen should follow",
                "Directive Principles — guidelines for the government to create a just society",
                "It is the longest written constitution in the world",
            ],
            "fun_fact": "The Indian Constitution is the longest written constitution in the world with 448 articles in 25 parts and 12 schedules!",
            "discussion_questions": [
                "Why is the Constitution important?",
                "What does the Preamble say?",
                "What are Fundamental Rights?",
            ],
        },
        {
            "num": 19,
            "title": "India's Democratic Government",
            "emoji": "🏛️",
            "wiki_queries": [
                "Parliament of India",
                "Lok Sabha",
                "Rajya Sabha",
                "President of India",
                "Prime Minister of India",
                "Union Cabinet India",
                "judiciary of India Supreme Court",
                "three pillars of democracy India",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "India is the largest democracy in the world",
                "Three pillars of democracy: Legislature, Executive, Judiciary",
                "Legislature (Parliament) — makes laws (Lok Sabha + Rajya Sabha)",
                "Lok Sabha — Lower House, elected directly by the people (543 members)",
                "Rajya Sabha — Upper House, elected by state legislatures (245 members)",
                "Executive — President (Head of State), Prime Minister (Head of Government)",
                "Judiciary — Supreme Court is the highest court, ensures laws are followed",
                "India follows a parliamentary system of government",
            ],
            "fun_fact": "India's first general election in 1951-52 was the largest democratic exercise in the world at that time — over 173 million people voted!",
            "discussion_questions": [
                "What are the three pillars of Indian democracy?",
                "What is the difference between Lok Sabha and Rajya Sabha?",
                "What is the role of the Prime Minister?",
            ],
        },
        {
            "num": 20,
            "title": "Elections in India",
            "emoji": "🗳️",
            "wiki_queries": [
                "Election Commission of India",
                "voting system India",
                "electoral process India",
                "electoral roll India",
                "EVM electronic voting machine India",
                "general elections India",
                "state elections India",
                "universal adult franchise India",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "Election Commission of India — conducts and manages all elections",
                "Universal Adult Franchise — every citizen above 18 years has the right to vote",
                "Types of Elections: General (Lok Sabha), State (Vidhan Sabha), Local (Panchayat/Municipal)",
                "Electoral Roll — list of all eligible voters in a constituency",
                "EVM (Electronic Voting Machine) — used for voting since 1999",
                "Voter ID Card — required to cast your vote",
                "Election process: Announcement → Nomination → Campaigning → Polling → Counting → Results",
                "India has 543 Lok Sabha constituencies",
            ],
            "fun_fact": "India uses over 1 million EVMs during a general election, making it the largest electronic voting exercise in the world!",
            "discussion_questions": [
                "What is the Election Commission of India?",
                "What is Universal Adult Franchise?",
                "How does an EVM work?",
            ],
        },
        {
            "num": 21,
            "title": "The United Nations",
            "emoji": "🌐",
            "wiki_queries": [
                "United Nations",
                "UN General Assembly",
                "UN Security Council",
                "UNICEF",
                "WHO World Health Organization",
                "UNESCO",
                "UN peacekeeping",
                "Sustainable Development Goals",
                "India and the United Nations",
            ],
            "trivia_categories": [23],
            "key_concepts": [
                "United Nations (UN) — an international organization formed in 1945 after World War II",
                "Headquarters: New York, USA",
                "Currently 193 member countries",
                "Main organs: General Assembly, Security Council, ECOSOC, ICJ, Secretariat",
                "Security Council — 5 permanent members (USA, UK, France, Russia, China) + 10 non-permanent",
                "UNICEF — works for children's rights, health, and education",
                "WHO — works for global health",
                "UNESCO — works for education, science, and culture",
                "India is a founding member of the UN and has been a non-permanent member of the Security Council 8 times",
                "Sustainable Development Goals (SDGs) — 17 goals to achieve by 2030",
            ],
            "fun_fact": "The UN has 6 official languages: Arabic, Chinese, English, French, Russian, and Spanish. India has contributed the most troops to UN peacekeeping missions!",
            "discussion_questions": [
                "Why was the United Nations formed?",
                "What are the main organs of the UN?",
                "How does India participate in the United Nations?",
            ],
        },
    ],
}

# Trivia category mapping for opentdb
TRIVIA_CATEGORY_MAP = {
    17: "Science",
    22: "Geography",
    23: "History",
}


def get_all_chapters():
    """Return flat list of all chapters across sections."""
    all_chaps = []
    for section, chapters in CHAPTERS.items():
        for ch in chapters:
            all_chaps.append({**ch, "section": section})
    return all_chaps


def get_chapter(section, chapter_num):
    """Get a specific chapter by section and number."""
    for ch in CHAPTERS.get(section, []):
        if ch["num"] == chapter_num:
            return {**ch, "section": section}
    return None


def get_sections():
    """Return list of section names."""
    return list(CHAPTERS.keys())